# Generated by Django 5.1.5 on 2025-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkeleza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='author_profiles/'),
        ),
    ]
