# Generated by Django 5.1.5 on 2025-01-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkeleza', '0002_article_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_location', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='author_profiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_location',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='author_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tkeleza.authorprofile'),
        ),
    ]
