# Generated by Django 5.1.5 on 2025-01-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkeleza', '0004_remove_article_author_profile_article_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_location',
            field=models.CharField(default='default_location', max_length=255),
        ),
    ]
